apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  minReadySeconds: 20
  selector:
    matchLabels:
      role: nginx
    matchExpressions:
      - {key: role, operator: In, values: [nginx]}
  template:
    metadata:
      name: nginx
      labels:
        role: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
