apiVersion: v1
kind: Service
metadata:
    name: nginx
    labels: 
        role: nginx
spec:
    selector: 
        role: nginx
    ports:
        - port: 80
          targetPort: 80
    type: LoadBalancer
